language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_script:
  - echo "deb http://llvm.org/apt/vivid/ llvm-toolchain-vivid-3.6 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb-src http://llvm.org/apt/vivid/ llvm-toolchain-vivid-3.6 main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y llvm-3.6-dev

script: make test && make config=release test

notifications:
  irc: "irc.freenode.org#ponylang"